apiVersion: v1
kind: Service
metadata:
  name: ratus-mongodb
  labels:
    app: ratus
spec:
  ports:
    - port: 27017
  selector:
    app: ratus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratus-mongodb
  labels:
    app: ratus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratus-mongodb
  labels:
    app: ratus
spec:
  selector:
    matchLabels:
      app: ratus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratus
    spec:
      containers:
        - image: mongo:4.4
          name: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /var/lib/mongodb
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: ratus-mongodb
