name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '4.4'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Test packages
        run: make test
      - name: Build artifacts
        run: make build
      - name: Run coverage
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        run: codecov/codecov-action@v3
